# Q2 count number of characters in a string
string="google.com"
g=string.count("g")
print("g-",g)
o=string.count("o")
print("o-",o)
l=string.count("l")
print("l-",l)
e=string.count("e")
print("e-",e)
dot=string.count(".")
print(".-",dot)
c=string.count("c")
print("c-",c)
m=string.count("m")
print("m-",m)